/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        "secondary": "#775a00",
        "tertiary-fixed-dim": "#ffb4a1",
        "on-tertiary-container": "#f87c5c",
        "surface": "#fbf8ff",
        "surface-container-high": "#e9e7f1",
        "on-error": "#ffffff",
        "tertiary": "#470b00",
        "primary": "#000f74",
        "navigation-dark": "#0A0F1D",
        "surface-container-lowest": "#ffffff",
        "border-whisper": "#E2E8F0",
        "primary-fixed-dim": "#bcc2ff",
        "tertiary-fixed": "#ffdbd2",
        "on-primary-container": "#8b98ff",
        "primary-fixed": "#dfe0ff",
        "on-secondary-container": "#6f5400",
        "destructive-asu": "#8B0942",
        "secondary-fixed": "#ffdf99",
        "error": "#ba1a1a",
        "destructive-alt": "#E11D48",
        "surface-variant": "#e3e1eb",
        "on-primary-fixed-variant": "#2938aa",
        "inverse-surface": "#303037",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2effa",
        "on-primary-fixed": "#000b62",
        "surface-container": "#FFFFFF",
        "on-secondary-fixed-variant": "#5a4300",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6d1600",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "text-secondary": "#64748B",
        "success-galala": "#A1D55D",
        "surface-container-low": "#f5f2fc",
        "error-container": "#ffdad6",
        "canvas-bg": "#F8FAFC",
        "on-tertiary-fixed-variant": "#83260c",
        "primary-container": "#14259b",
        "surface-dim": "#dbd9e3",
        "outline": "#767685",
        "on-surface-variant": "#454653",
        "surface-container-highest": "#e3e1eb",
        "secondary-fixed-dim": "#f4bf2c",
        "text-primary": "#0F172A",
        "inverse-primary": "#bcc2ff",
        "surface-bright": "#fbf8ff",
        "background": "#fbf8ff",
        "on-tertiary-fixed": "#3c0800",
        "secondary-container": "#fdc735",
        "on-secondary-fixed": "#251a00",
        "on-surface": "#1b1b22",
        "on-background": "#1b1b22",
        "outline-variant": "#c6c5d5",
        "surface-tint": "#4452c3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "4px",
        "max-width": "1440px"
      },
      fontFamily: {
        "display-lg": ["Outfit"],
        "body-lg": ["Outfit"],
        "display-lg-mobile": ["Outfit"],
        "headline-md": ["Outfit"],
        "label-mono-sm": ["JetBrains Mono"],
        "body-sm": ["Outfit"],
        "label-mono": ["JetBrains Mono"],
        "headline-sm": ["Outfit"],
        "body-md": ["Outfit"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-mono-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
